name: MLflow-AutoML 
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
dependencies:
  - python=3.8.2
  - pip
  - pip:
    - mlflow 
    - click==8.0.3
    - scikit-learn==0.24.2 
    - boto3==1.22.2 
    - pandas>=1.0.0 
    - setuptools<59.6.0
    - auto-sklearn==0.14.6
    - flaml==1.0.1
