github:
  description: MLFlow examples for Apache Dolphinscheduler
  homepage: https://dolphinscheduler.apache.org/
  labels:
    - dolphinscheduler
    - MLops
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  protected_branches:
    main:
      required_status_checks:
        strict: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1

notifications:
  commits:      commits@dolphinscheduler.apache.org
  issues:       commits@dolphinscheduler.apache.org
  pullrequests: commits@dolphinscheduler.apache.org
  pullrequests_status:  commits@dolphinscheduler.apache.org
  pullrequests_comment: commits@dolphinscheduler.apache.org