name: sklearn
channels:
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
dependencies:

  - numpy>=1.14.3
  - pandas>=1.0.0
  - scikit-learn=1.0.2
  - pip
  - pip:
    - mlflow
    - click
    - lightgbm
    - Pillow
    - xgboost==1.5.2
    - boto3


